name: CI

on:
  push:
    # Run for any pushs on master
    branches:
      - master
  # Run tests for any PRs.
  pull_request:

jobs:
  run-tests:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
      - name: Install Packages
        run: yarn install
      - name: Run Prettier
        run: yarn fmt:check
      - name: Run eslint
        run: yarn lint:check
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun
