name: CI

on:
  push:
    # Run for any pushs on master
    branches:
      - master
  # Run tests for any PRs.
  pull_request:

jobs:
  run-tests:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
      - name: Install Packages
        run: npm install
      - name: Run Prettier
        run:  npm run fmt:check
      - name: Run eslint
        run: npm run lint:check
